!/bin/sh

# xinitrc runs automatically when you run startx.

export _JAVA_AWT_WM_NONREPARENTING=1
setxkbmap gb
clipmenud &
slstatus &
flameshot &
dunst &
kopia server --insecure --without-password &
xrandr --output DP-0 --mode 1920x1080 --pos 0x0 --rate 200 --output DP-4 --primary --mode 1920x1080 --pos 1920x0 --rate 200 --output DP-2 --mode 1920x1080 --pos 3840x0 --rate 200
blueman-applet &
easyeffects --gapplication-service &

while sleep 1
do
    xsetroot -name $(date)
done &

while sleep 1
do
    picom --config ~/.config/picom.conf
done &

wal -i ~/.local/share/wallpapers --saturate 1

while :; do
        ssh-agent dwm
done
