#!/bin/sh

# xinitrc runs automatically when you run startx.

export _JAVA_AWT_WM_NONREPARENTING=1
setxkbmap gb
clipmenud &
slstatus &
flameshot &
dunst &
kopia server --insecure --without-password &
xrandr --output DP-0 --mode 1920x1080 --refresh 240.00 --output DP-2 --mode 1920x1080 --refresh 240.00 --output DP-4 --mode 1920x1080 --refresh 240.00
blueman-applet &

while sleep 1
do
    xsetroot -name $(date)
done &

while sleep 1
do
    picom --config ~/.config/picom.conf
done &

wal -i ~/.local/share/wallpapers --saturate 1

while :; do
        ssh-agent dwm
done
